# Generated by Django 4.0.2 on 2022-03-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarytagpermission',
            old_name='endtdate',
            new_name='enddate',
        ),
    ]
