# Generated by Django 4.0 on 2022-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTagPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.TextField()),
                ('endtdate', models.TextField()),
                ('item', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('tel', models.CharField(max_length=10)),
                ('supervisor', models.TextField(blank=True, null=True)),
                ('approveplant', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
